export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAIL = "FETCH_MESSAGES_FAIL";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";



