export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const FETCH_TAGS_REQUEST = "FETCH_TAGS_REQUEST";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_FAIL = "FETCH_TAGS_FAIL";

export const FETCH_A_POST_REQUEST = "FETCH_A_POST_REQUEST";
export const FETCH_A_POST_SUCCESS = "FETCH_A_POST_SUCCESS";
export const FETCH_A_POST_FAIL = "FETCH_A_POST_FAIL";

export const UPDATE_A_POST_REQUEST = "UPDATE_A_POST_REQUEST";
export const UPDATE_A_POST_SUCCESS = "UPDATE_A_POST_SUCCESS";
export const UPDATE_A_POST_FAIL = "UPDATE_A_POST_FAIL";

export const DELETE_A_POST_REQUEST = "DELETE_A_POST_REQUEST";
export const DELETE_A_POST_SUCCESS = "DELETE_A_POST_SUCCESS";
export const DELETE_A_POST_FAIL = "DELETE_A_POST_FAIL";

export const GET_POST_REVIEWS_REQUEST = "GET_POST_REVIEWS_REQUEST";
export const GET_POST_REVIEWS_SUCCESS = "GET_POST_REVIEWS_SUCCESS";
export const GET_POST_REVIEWS_FAIL = "GET_POST_REVIEWS_FAIL";

export const LIKE_A_POST_REQUEST = "LIKE_A_POST_REQUEST";
export const LIKE_A_POST_SUCCESS = "LIKE_A_POST_SUCCESS";
export const LIKE_A_POST_FAIL = "LIKE_A_POST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const FETCH_FOLLOWING_POSTS_REQUEST = "FETCH_FOLLOWING_POSTS_REQUEST";
export const FETCH_FOLLOWING_POSTS_SUCCESS = "FETCH_FOLLOWING_POSTS_SUCCESS";
export const FETCH_FOLLOWING_POSTS_FAIL = "FETCH_FOLLOWING_POSTS_FAIL";


